import type { TSchema } from "typebox";
import {
  AgentEventSchema,
  AgentIdentityParamsSchema,
  AgentIdentityResultSchema,
  AgentParamsSchema,
  AgentWaitParamsSchema,
  MessageActionParamsSchema,
  PollParamsSchema,
  SendParamsSchema,
  WakeParamsSchema,
} from "./agent.js";
import {
  AgentSummarySchema,
  AgentsCreateParamsSchema,
  AgentsCreateResultSchema,
  AgentsDeleteParamsSchema,
  AgentsDeleteResultSchema,
  AgentsFileEntrySchema,
  AgentsFilesGetParamsSchema,
  AgentsFilesGetResultSchema,
  AgentsFilesListParamsSchema,
  AgentsFilesListResultSchema,
  AgentsFilesSetParamsSchema,
  AgentsFilesSetResultSchema,
  AgentsListParamsSchema,
  AgentsListResultSchema,
  AgentsUpdateParamsSchema,
  AgentsUpdateResultSchema,
  ModelChoiceSchema,
  ModelsListParamsSchema,
  ModelsListResultSchema,
  SkillsBinsParamsSchema,
  SkillsBinsResultSchema,
  SkillsDetailParamsSchema,
  SkillsDetailResultSchema,
  SkillsInstallParamsSchema,
  SkillsProposalActionParamsSchema,
  SkillsProposalApplyResultSchema,
  SkillsProposalCreateParamsSchema,
  SkillsProposalInspectParamsSchema,
  SkillsProposalInspectResultSchema,
  SkillsProposalRecordResultSchema,
  SkillsProposalReviseParamsSchema,
  SkillsProposalUpdateParamsSchema,
  SkillsProposalsListParamsSchema,
  SkillsProposalsListResultSchema,
  SkillsSearchParamsSchema,
  SkillsSearchResultSchema,
  SkillsSecurityVerdictsParamsSchema,
  SkillsSecurityVerdictsResultSchema,
  SkillsSkillCardParamsSchema,
  SkillsSkillCardResultSchema,
  SkillsStatusParamsSchema,
  SkillsUploadBeginParamsSchema,
  SkillsUploadChunkParamsSchema,
  SkillsUploadCommitParamsSchema,
  SkillsUpdateParamsSchema,
  ToolCatalogEntrySchema,
  ToolCatalogGroupSchema,
  ToolCatalogProfileSchema,
  ToolsCatalogParamsSchema,
  ToolsCatalogResultSchema,
  ToolsEffectiveEntrySchema,
  ToolsEffectiveGroupSchema,
  ToolsEffectiveNoticeSchema,
  ToolsEffectiveParamsSchema,
  ToolsEffectiveResultSchema,
  ToolsInvokeErrorSchema,
  ToolsInvokeParamsSchema,
  ToolsInvokeResultSchema,
} from "./agents-models-skills.js";
import {
  ArtifactSummarySchema,
  ArtifactsDownloadParamsSchema,
  ArtifactsDownloadResultSchema,
  ArtifactsGetParamsSchema,
  ArtifactsGetResultSchema,
  ArtifactsListParamsSchema,
  ArtifactsListResultSchema,
} from "./artifacts.js";
import {
  ChannelsStartParamsSchema,
  ChannelsStopParamsSchema,
  ChannelsLogoutParamsSchema,
  TalkEventSchema,
  TalkCatalogParamsSchema,
  TalkCatalogResultSchema,
  TalkClientCreateParamsSchema,
  TalkClientCreateResultSchema,
  TalkAgentControlResultSchema,
  TalkClientSteerParamsSchema,
  TalkClientToolCallParamsSchema,
  TalkClientToolCallResultSchema,
  TalkConfigParamsSchema,
  TalkConfigResultSchema,
  TalkSessionAppendAudioParamsSchema,
  TalkSessionCancelOutputParamsSchema,
  TalkSessionCancelTurnParamsSchema,
  TalkSessionCloseParamsSchema,
  TalkSessionCreateParamsSchema,
  TalkSessionCreateResultSchema,
  TalkSessionJoinParamsSchema,
  TalkSessionJoinResultSchema,
  TalkSessionOkResultSchema,
  TalkSessionSteerParamsSchema,
  TalkSessionSubmitToolResultParamsSchema,
  TalkSessionTurnResultSchema,
  TalkSessionTurnParamsSchema,
  TalkSpeakParamsSchema,
  TalkSpeakResultSchema,
  ChannelsStatusParamsSchema,
  ChannelsStatusResultSchema,
  TalkModeParamsSchema,
  WebLoginStartParamsSchema,
  WebLoginWaitParamsSchema,
} from "./channels.js";
import {
  CommandEntrySchema,
  CommandsListParamsSchema,
  CommandsListResultSchema,
} from "./commands.js";
import {
  ConfigApplyParamsSchema,
  ConfigGetParamsSchema,
  ConfigPatchParamsSchema,
  ConfigSchemaLookupParamsSchema,
  ConfigSchemaLookupResultSchema,
  ConfigSchemaParamsSchema,
  ConfigSchemaResponseSchema,
  ConfigSetParamsSchema,
  UpdateStatusParamsSchema,
  UpdateRunParamsSchema,
} from "./config.js";
import {
  CronAddParamsSchema,
  CronGetParamsSchema,
  CronJobSchema,
  CronListParamsSchema,
  CronRemoveParamsSchema,
  CronRunLogEntrySchema,
  CronRunParamsSchema,
  CronRunsParamsSchema,
  CronStatusParamsSchema,
  CronUpdateParamsSchema,
} from "./cron.js";
import {
  DevicePairApproveParamsSchema,
  DevicePairListParamsSchema,
  DevicePairRemoveParamsSchema,
  DevicePairRejectParamsSchema,
  DevicePairRequestedEventSchema,
  DevicePairResolvedEventSchema,
  DeviceTokenRevokeParamsSchema,
  DeviceTokenRotateParamsSchema,
} from "./devices.js";
import {
  EnvironmentSummarySchema,
  EnvironmentsListParamsSchema,
  EnvironmentsListResultSchema,
  EnvironmentsStatusParamsSchema,
  EnvironmentsStatusResultSchema,
  EnvironmentStatusSchema,
} from "./environments.js";
import {
  ExecApprovalsGetParamsSchema,
  ExecApprovalsNodeGetParamsSchema,
  ExecApprovalsNodeSetParamsSchema,
  ExecApprovalsSetParamsSchema,
  ExecApprovalsSnapshotSchema,
  ExecApprovalGetParamsSchema,
  ExecApprovalRequestParamsSchema,
  ExecApprovalResolveParamsSchema,
} from "./exec-approvals.js";
import {
  ConnectParamsSchema,
  ErrorShapeSchema,
  EventFrameSchema,
  GatewayFrameSchema,
  HelloOkSchema,
  RequestFrameSchema,
  ResponseFrameSchema,
  ShutdownEventSchema,
  TickEventSchema,
} from "./frames.js";
import {
  ChatAbortedEventSchema,
  ChatAbortParamsSchema,
  ChatDeltaEventSchema,
  ChatErrorEventSchema,
  ChatEventSchema,
  ChatFinalEventSchema,
  ChatHistoryParamsSchema,
  ChatMessageGetParamsSchema,
  ChatMessageGetResultSchema,
  ChatInjectParamsSchema,
  ChatSendParamsSchema,
  LogsTailParamsSchema,
  LogsTailResultSchema,
} from "./logs-chat.js";
import {
  NodeDescribeParamsSchema,
  NodeEventParamsSchema,
  NodeEventResultSchema,
  NodePendingDrainParamsSchema,
  NodePendingDrainResultSchema,
  NodePendingEnqueueParamsSchema,
  NodePendingEnqueueResultSchema,
  NodePresenceAlivePayloadSchema,
  NodePresenceAliveReasonSchema,
  NodeInvokeParamsSchema,
  NodeInvokeResultParamsSchema,
  NodeInvokeRequestEventSchema,
  NodeListParamsSchema,
  NodePendingAckParamsSchema,
  NodePairApproveParamsSchema,
  NodePairListParamsSchema,
  NodePairRemoveParamsSchema,
  NodePairRejectParamsSchema,
  NodePairRequestParamsSchema,
  NodePairVerifyParamsSchema,
  NodeRenameParamsSchema,
} from "./nodes.js";
import {
  PluginApprovalRequestParamsSchema,
  PluginApprovalResolveParamsSchema,
} from "./plugin-approvals.js";
import {
  PluginControlUiDescriptorSchema,
  PluginsSessionActionFailureResultSchema,
  PluginsSessionActionParamsSchema,
  PluginsSessionActionResultSchema,
  PluginsSessionActionSuccessResultSchema,
  PluginsUiDescriptorsParamsSchema,
  PluginsUiDescriptorsResultSchema,
} from "./plugins.js";
import { PushTestParamsSchema, PushTestResultSchema } from "./push.js";
import {
  SecretsReloadParamsSchema,
  SecretsResolveAssignmentSchema,
  SecretsResolveParamsSchema,
  SecretsResolveResultSchema,
} from "./secrets.js";
import {
  SessionsAbortParamsSchema,
  SessionsCompactParamsSchema,
  SessionsCompactionBranchParamsSchema,
  SessionsCompactionBranchResultSchema,
  SessionsCompactionGetParamsSchema,
  SessionsCompactionGetResultSchema,
  SessionsCompactionListParamsSchema,
  SessionsCompactionListResultSchema,
  SessionsCompactionRestoreParamsSchema,
  SessionsCompactionRestoreResultSchema,
  SessionCompactionCheckpointSchema,
  SessionOperationEventSchema,
  SessionsCleanupParamsSchema,
  SessionsCreateParamsSchema,
  SessionsDeleteParamsSchema,
  SessionsDescribeParamsSchema,
  SessionsListParamsSchema,
  SessionsMessagesSubscribeParamsSchema,
  SessionsMessagesUnsubscribeParamsSchema,
  SessionsPatchParamsSchema,
  SessionsPluginPatchParamsSchema,
  SessionsPluginPatchResultSchema,
  SessionsPreviewParamsSchema,
  SessionsResetParamsSchema,
  SessionsResolveParamsSchema,
  SessionsSendParamsSchema,
  SessionsUsageParamsSchema,
} from "./sessions.js";
import { PresenceEntrySchema, SnapshotSchema, StateVersionSchema } from "./snapshot.js";
import {
  TasksCancelParamsSchema,
  TasksCancelResultSchema,
  TasksGetParamsSchema,
  TasksGetResultSchema,
  TasksListParamsSchema,
  TasksListResultSchema,
  TaskSummarySchema,
} from "./tasks.js";
import {
  WizardCancelParamsSchema,
  WizardNextParamsSchema,
  WizardNextResultSchema,
  WizardStartParamsSchema,
  WizardStartResultSchema,
  WizardStatusParamsSchema,
  WizardStatusResultSchema,
  WizardStepSchema,
} from "./wizard.js";

export const ProtocolSchemas = {
  ConnectParams: ConnectParamsSchema,
  HelloOk: HelloOkSchema,
  RequestFrame: RequestFrameSchema,
  ResponseFrame: ResponseFrameSchema,
  EventFrame: EventFrameSchema,
  GatewayFrame: GatewayFrameSchema,
  PresenceEntry: PresenceEntrySchema,
  StateVersion: StateVersionSchema,
  Snapshot: SnapshotSchema,
  ErrorShape: ErrorShapeSchema,
  EnvironmentStatus: EnvironmentStatusSchema,
  EnvironmentSummary: EnvironmentSummarySchema,
  EnvironmentsListParams: EnvironmentsListParamsSchema,
  EnvironmentsListResult: EnvironmentsListResultSchema,
  EnvironmentsStatusParams: EnvironmentsStatusParamsSchema,
  EnvironmentsStatusResult: EnvironmentsStatusResultSchema,
  AgentEvent: AgentEventSchema,
  MessageActionParams: MessageActionParamsSchema,
  SendParams: SendParamsSchema,
  PollParams: PollParamsSchema,
  AgentParams: AgentParamsSchema,
  AgentIdentityParams: AgentIdentityParamsSchema,
  AgentIdentityResult: AgentIdentityResultSchema,
  AgentWaitParams: AgentWaitParamsSchema,
  WakeParams: WakeParamsSchema,
  NodePairRequestParams: NodePairRequestParamsSchema,
  NodePairListParams: NodePairListParamsSchema,
  NodePairApproveParams: NodePairApproveParamsSchema,
  NodePairRejectParams: NodePairRejectParamsSchema,
  NodePairRemoveParams: NodePairRemoveParamsSchema,
  NodePairVerifyParams: NodePairVerifyParamsSchema,
  NodeRenameParams: NodeRenameParamsSchema,
  NodeListParams: NodeListParamsSchema,
  NodePendingAckParams: NodePendingAckParamsSchema,
  NodeDescribeParams: NodeDescribeParamsSchema,
  NodeInvokeParams: NodeInvokeParamsSchema,
  NodeInvokeResultParams: NodeInvokeResultParamsSchema,
  NodeEventParams: NodeEventParamsSchema,
  NodeEventResult: NodeEventResultSchema,
  NodePresenceAlivePayload: NodePresenceAlivePayloadSchema,
  NodePresenceAliveReason: NodePresenceAliveReasonSchema,
  NodePendingDrainParams: NodePendingDrainParamsSchema,
  NodePendingDrainResult: NodePendingDrainResultSchema,
  NodePendingEnqueueParams: NodePendingEnqueueParamsSchema,
  NodePendingEnqueueResult: NodePendingEnqueueResultSchema,
  NodeInvokeRequestEvent: NodeInvokeRequestEventSchema,
  PushTestParams: PushTestParamsSchema,
  PushTestResult: PushTestResultSchema,
  SecretsReloadParams: SecretsReloadParamsSchema,
  SecretsResolveParams: SecretsResolveParamsSchema,
  SecretsResolveAssignment: SecretsResolveAssignmentSchema,
  SecretsResolveResult: SecretsResolveResultSchema,
  SessionsListParams: SessionsListParamsSchema,
  SessionsCleanupParams: SessionsCleanupParamsSchema,
  SessionsPreviewParams: SessionsPreviewParamsSchema,
  SessionsDescribeParams: SessionsDescribeParamsSchema,
  SessionsResolveParams: SessionsResolveParamsSchema,
  SessionCompactionCheckpoint: SessionCompactionCheckpointSchema,
  SessionOperationEvent: SessionOperationEventSchema,
  SessionsCompactionListParams: SessionsCompactionListParamsSchema,
  SessionsCompactionGetParams: SessionsCompactionGetParamsSchema,
  SessionsCompactionBranchParams: SessionsCompactionBranchParamsSchema,
  SessionsCompactionRestoreParams: SessionsCompactionRestoreParamsSchema,
  SessionsCompactionListResult: SessionsCompactionListResultSchema,
  SessionsCompactionGetResult: SessionsCompactionGetResultSchema,
  SessionsCompactionBranchResult: SessionsCompactionBranchResultSchema,
  SessionsCompactionRestoreResult: SessionsCompactionRestoreResultSchema,
  SessionsCreateParams: SessionsCreateParamsSchema,
  SessionsSendParams: SessionsSendParamsSchema,
  SessionsMessagesSubscribeParams: SessionsMessagesSubscribeParamsSchema,
  SessionsMessagesUnsubscribeParams: SessionsMessagesUnsubscribeParamsSchema,
  SessionsAbortParams: SessionsAbortParamsSchema,
  SessionsPatchParams: SessionsPatchParamsSchema,
  SessionsPluginPatchParams: SessionsPluginPatchParamsSchema,
  SessionsPluginPatchResult: SessionsPluginPatchResultSchema,
  SessionsResetParams: SessionsResetParamsSchema,
  SessionsDeleteParams: SessionsDeleteParamsSchema,
  SessionsCompactParams: SessionsCompactParamsSchema,
  SessionsUsageParams: SessionsUsageParamsSchema,
  TaskSummary: TaskSummarySchema,
  TasksListParams: TasksListParamsSchema,
  TasksListResult: TasksListResultSchema,
  TasksGetParams: TasksGetParamsSchema,
  TasksGetResult: TasksGetResultSchema,
  TasksCancelParams: TasksCancelParamsSchema,
  TasksCancelResult: TasksCancelResultSchema,
  ConfigGetParams: ConfigGetParamsSchema,
  ConfigSetParams: ConfigSetParamsSchema,
  ConfigApplyParams: ConfigApplyParamsSchema,
  ConfigPatchParams: ConfigPatchParamsSchema,
  ConfigSchemaParams: ConfigSchemaParamsSchema,
  ConfigSchemaLookupParams: ConfigSchemaLookupParamsSchema,
  ConfigSchemaResponse: ConfigSchemaResponseSchema,
  ConfigSchemaLookupResult: ConfigSchemaLookupResultSchema,
  WizardStartParams: WizardStartParamsSchema,
  WizardNextParams: WizardNextParamsSchema,
  WizardCancelParams: WizardCancelParamsSchema,
  WizardStatusParams: WizardStatusParamsSchema,
  WizardStep: WizardStepSchema,
  WizardNextResult: WizardNextResultSchema,
  WizardStartResult: WizardStartResultSchema,
  WizardStatusResult: WizardStatusResultSchema,
  TalkModeParams: TalkModeParamsSchema,
  TalkEvent: TalkEventSchema,
  TalkCatalogParams: TalkCatalogParamsSchema,
  TalkCatalogResult: TalkCatalogResultSchema,
  TalkClientCreateParams: TalkClientCreateParamsSchema,
  TalkClientCreateResult: TalkClientCreateResultSchema,
  TalkClientSteerParams: TalkClientSteerParamsSchema,
  TalkAgentControlResult: TalkAgentControlResultSchema,
  TalkClientToolCallParams: TalkClientToolCallParamsSchema,
  TalkClientToolCallResult: TalkClientToolCallResultSchema,
  TalkConfigParams: TalkConfigParamsSchema,
  TalkConfigResult: TalkConfigResultSchema,
  TalkSessionAppendAudioParams: TalkSessionAppendAudioParamsSchema,
  TalkSessionCancelOutputParams: TalkSessionCancelOutputParamsSchema,
  TalkSessionCancelTurnParams: TalkSessionCancelTurnParamsSchema,
  TalkSessionCreateParams: TalkSessionCreateParamsSchema,
  TalkSessionCreateResult: TalkSessionCreateResultSchema,
  TalkSessionJoinParams: TalkSessionJoinParamsSchema,
  TalkSessionJoinResult: TalkSessionJoinResultSchema,
  TalkSessionTurnParams: TalkSessionTurnParamsSchema,
  TalkSessionTurnResult: TalkSessionTurnResultSchema,
  TalkSessionSteerParams: TalkSessionSteerParamsSchema,
  TalkSessionSubmitToolResultParams: TalkSessionSubmitToolResultParamsSchema,
  TalkSessionCloseParams: TalkSessionCloseParamsSchema,
  TalkSessionOkResult: TalkSessionOkResultSchema,
  TalkSpeakParams: TalkSpeakParamsSchema,
  TalkSpeakResult: TalkSpeakResultSchema,
  ChannelsStatusParams: ChannelsStatusParamsSchema,
  ChannelsStatusResult: ChannelsStatusResultSchema,
  ChannelsStartParams: ChannelsStartParamsSchema,
  ChannelsStopParams: ChannelsStopParamsSchema,
  ChannelsLogoutParams: ChannelsLogoutParamsSchema,
  WebLoginStartParams: WebLoginStartParamsSchema,
  WebLoginWaitParams: WebLoginWaitParamsSchema,
  AgentSummary: AgentSummarySchema,
  AgentsCreateParams: AgentsCreateParamsSchema,
  AgentsCreateResult: AgentsCreateResultSchema,
  AgentsUpdateParams: AgentsUpdateParamsSchema,
  AgentsUpdateResult: AgentsUpdateResultSchema,
  AgentsDeleteParams: AgentsDeleteParamsSchema,
  AgentsDeleteResult: AgentsDeleteResultSchema,
  AgentsFileEntry: AgentsFileEntrySchema,
  AgentsFilesListParams: AgentsFilesListParamsSchema,
  AgentsFilesListResult: AgentsFilesListResultSchema,
  AgentsFilesGetParams: AgentsFilesGetParamsSchema,
  AgentsFilesGetResult: AgentsFilesGetResultSchema,
  AgentsFilesSetParams: AgentsFilesSetParamsSchema,
  AgentsFilesSetResult: AgentsFilesSetResultSchema,
  ArtifactSummary: ArtifactSummarySchema,
  ArtifactsListParams: ArtifactsListParamsSchema,
  ArtifactsListResult: ArtifactsListResultSchema,
  ArtifactsGetParams: ArtifactsGetParamsSchema,
  ArtifactsGetResult: ArtifactsGetResultSchema,
  ArtifactsDownloadParams: ArtifactsDownloadParamsSchema,
  ArtifactsDownloadResult: ArtifactsDownloadResultSchema,
  AgentsListParams: AgentsListParamsSchema,
  AgentsListResult: AgentsListResultSchema,
  ModelChoice: ModelChoiceSchema,
  ModelsListParams: ModelsListParamsSchema,
  ModelsListResult: ModelsListResultSchema,
  CommandEntry: CommandEntrySchema,
  CommandsListParams: CommandsListParamsSchema,
  CommandsListResult: CommandsListResultSchema,
  SkillsStatusParams: SkillsStatusParamsSchema,
  ToolsCatalogParams: ToolsCatalogParamsSchema,
  ToolCatalogProfile: ToolCatalogProfileSchema,
  ToolCatalogEntry: ToolCatalogEntrySchema,
  ToolCatalogGroup: ToolCatalogGroupSchema,
  ToolsCatalogResult: ToolsCatalogResultSchema,
  ToolsEffectiveParams: ToolsEffectiveParamsSchema,
  ToolsEffectiveEntry: ToolsEffectiveEntrySchema,
  ToolsEffectiveGroup: ToolsEffectiveGroupSchema,
  ToolsEffectiveNotice: ToolsEffectiveNoticeSchema,
  ToolsEffectiveResult: ToolsEffectiveResultSchema,
  ToolsInvokeParams: ToolsInvokeParamsSchema,
  ToolsInvokeError: ToolsInvokeErrorSchema,
  ToolsInvokeResult: ToolsInvokeResultSchema,
  SkillsBinsParams: SkillsBinsParamsSchema,
  SkillsBinsResult: SkillsBinsResultSchema,
  SkillsSearchParams: SkillsSearchParamsSchema,
  SkillsSearchResult: SkillsSearchResultSchema,
  SkillsDetailParams: SkillsDetailParamsSchema,
  SkillsDetailResult: SkillsDetailResultSchema,
  SkillsProposalsListParams: SkillsProposalsListParamsSchema,
  SkillsProposalsListResult: SkillsProposalsListResultSchema,
  SkillsProposalInspectParams: SkillsProposalInspectParamsSchema,
  SkillsProposalInspectResult: SkillsProposalInspectResultSchema,
  SkillsProposalCreateParams: SkillsProposalCreateParamsSchema,
  SkillsProposalUpdateParams: SkillsProposalUpdateParamsSchema,
  SkillsProposalReviseParams: SkillsProposalReviseParamsSchema,
  SkillsProposalActionParams: SkillsProposalActionParamsSchema,
  SkillsProposalApplyResult: SkillsProposalApplyResultSchema,
  SkillsProposalRecordResult: SkillsProposalRecordResultSchema,
  SkillsSecurityVerdictsParams: SkillsSecurityVerdictsParamsSchema,
  SkillsSecurityVerdictsResult: SkillsSecurityVerdictsResultSchema,
  SkillsSkillCardParams: SkillsSkillCardParamsSchema,
  SkillsSkillCardResult: SkillsSkillCardResultSchema,
  SkillsUploadBeginParams: SkillsUploadBeginParamsSchema,
  SkillsUploadChunkParams: SkillsUploadChunkParamsSchema,
  SkillsUploadCommitParams: SkillsUploadCommitParamsSchema,
  SkillsInstallParams: SkillsInstallParamsSchema,
  SkillsUpdateParams: SkillsUpdateParamsSchema,
  CronJob: CronJobSchema,
  CronListParams: CronListParamsSchema,
  CronStatusParams: CronStatusParamsSchema,
  CronGetParams: CronGetParamsSchema,
  CronAddParams: CronAddParamsSchema,
  CronUpdateParams: CronUpdateParamsSchema,
  CronRemoveParams: CronRemoveParamsSchema,
  CronRunParams: CronRunParamsSchema,
  CronRunsParams: CronRunsParamsSchema,
  CronRunLogEntry: CronRunLogEntrySchema,
  LogsTailParams: LogsTailParamsSchema,
  LogsTailResult: LogsTailResultSchema,
  ExecApprovalsGetParams: ExecApprovalsGetParamsSchema,
  ExecApprovalsSetParams: ExecApprovalsSetParamsSchema,
  ExecApprovalsNodeGetParams: ExecApprovalsNodeGetParamsSchema,
  ExecApprovalsNodeSetParams: ExecApprovalsNodeSetParamsSchema,
  ExecApprovalsSnapshot: ExecApprovalsSnapshotSchema,
  ExecApprovalGetParams: ExecApprovalGetParamsSchema,
  ExecApprovalRequestParams: ExecApprovalRequestParamsSchema,
  ExecApprovalResolveParams: ExecApprovalResolveParamsSchema,
  PluginApprovalRequestParams: PluginApprovalRequestParamsSchema,
  PluginApprovalResolveParams: PluginApprovalResolveParamsSchema,
  PluginControlUiDescriptor: PluginControlUiDescriptorSchema,
  PluginsSessionActionFailureResult: PluginsSessionActionFailureResultSchema,
  PluginsSessionActionParams: PluginsSessionActionParamsSchema,
  PluginsSessionActionResult: PluginsSessionActionResultSchema,
  PluginsSessionActionSuccessResult: PluginsSessionActionSuccessResultSchema,
  PluginsUiDescriptorsParams: PluginsUiDescriptorsParamsSchema,
  PluginsUiDescriptorsResult: PluginsUiDescriptorsResultSchema,
  DevicePairListParams: DevicePairListParamsSchema,
  DevicePairApproveParams: DevicePairApproveParamsSchema,
  DevicePairRejectParams: DevicePairRejectParamsSchema,
  DevicePairRemoveParams: DevicePairRemoveParamsSchema,
  DeviceTokenRotateParams: DeviceTokenRotateParamsSchema,
  DeviceTokenRevokeParams: DeviceTokenRevokeParamsSchema,
  DevicePairRequestedEvent: DevicePairRequestedEventSchema,
  DevicePairResolvedEvent: DevicePairResolvedEventSchema,
  ChatHistoryParams: ChatHistoryParamsSchema,
  ChatMessageGetParams: ChatMessageGetParamsSchema,
  ChatMessageGetResult: ChatMessageGetResultSchema,
  ChatSendParams: ChatSendParamsSchema,
  ChatAbortParams: ChatAbortParamsSchema,
  ChatInjectParams: ChatInjectParamsSchema,
  ChatDeltaEvent: ChatDeltaEventSchema,
  ChatFinalEvent: ChatFinalEventSchema,
  ChatAbortedEvent: ChatAbortedEventSchema,
  ChatErrorEvent: ChatErrorEventSchema,
  ChatEvent: ChatEventSchema,
  UpdateStatusParams: UpdateStatusParamsSchema,
  UpdateRunParams: UpdateRunParamsSchema,
  TickEvent: TickEventSchema,
  ShutdownEvent: ShutdownEventSchema,
} satisfies Record<string, TSchema>;

export {
  MIN_CLIENT_PROTOCOL_VERSION,
  MIN_PROBE_PROTOCOL_VERSION,
  PROTOCOL_VERSION,
} from "../version.js";
