export const POLICY_TOOL_GROUPS: Record<string, readonly string[]> = {
  "group:openclaw": [
    "code_execution",
    "web_search",
    "web_fetch",
    "x_search",
    "memory_search",
    "memory_get",
    "sessions_list",
    "sessions_history",
    "sessions_send",
    "sessions_spawn",
    "sessions_yield",
    "subagents",
    "session_status",
    "browser",
    "message",
    "heartbeat_respond",
    "cron",
    "gateway",
    "nodes",
    "agents_list",
    "update_plan",
    "image",
    "image_generate",
    "music_generate",
    "video_generate",
    "tts",
  ],
  "group:fs": ["read", "write", "edit", "apply_patch"],
  "group:runtime": ["exec", "process", "code_execution"],
  "group:web": ["web_search", "web_fetch", "x_search"],
  "group:memory": ["memory_search", "memory_get"],
  "group:sessions": [
    "sessions_list",
    "sessions_history",
    "sessions_send",
    "sessions_spawn",
    "sessions_yield",
    "subagents",
    "session_status",
  ],
  "group:ui": ["browser", "canvas"],
  "group:messaging": ["message"],
  "group:automation": ["heartbeat_respond", "cron", "gateway"],
  "group:nodes": ["nodes"],
  "group:agents": ["agents_list", "update_plan"],
  "group:media": ["image", "image_generate", "music_generate", "video_generate", "tts"],
} as const;
