// Focused public config shape types used by bundled and third-party plugins.

export type { ChannelGroupPolicy } from "../config/group-policy.js";
export type { SessionScope } from "../config/sessions/types.js";
export type {
  AccessGroupsConfig,
  AuthConfig,
  BlockStreamingCoalesceConfig,
  BrowserConfig,
  BrowserProfileConfig,
  ChannelBotLoopProtectionConfig,
  ContextVisibilityMode,
  DiscordAccountConfig,
  DiscordActionConfig,
  DiscordAutoPresenceConfig,
  DiscordConfig,
  DiscordExecApprovalConfig,
  DiscordGuildChannelConfig,
  DiscordGuildEntry,
  DiscordIntentsConfig,
  DiscordSlashCommandConfig,
  DmConfig,
  DmPolicy,
  GoogleChatAccountConfig,
  GoogleChatConfig,
  GroupPolicy,
  GroupToolPolicyBySenderConfig,
  GroupToolPolicyConfig,
  MarkdownConfig,
  MarkdownTableMode,
  MentionPatternsPolicyConfig,
  MSTeamsChannelConfig,
  MSTeamsCloudName,
  MSTeamsConfig,
  MSTeamsReplyStyle,
  MSTeamsTeamConfig,
  OpenClawConfig,
  ReplyToMode,
  ResolvedTtsPersona,
  SignalReactionNotificationMode,
  SlackAccountConfig,
  SlackChannelConfig,
  SlackReactionNotificationMode,
  SlackSlashCommandConfig,
  TelegramAccountConfig,
  TelegramActionConfig,
  TelegramDirectConfig,
  TelegramDmThreadReplies,
  TelegramExecApprovalConfig,
  TelegramGroupConfig,
  TelegramInlineButtonsScope,
  TelegramNetworkConfig,
  TelegramTopicConfig,
  TtsAutoMode,
  TtsConfig,
  TtsModelOverrideConfig,
  TtsProvider,
} from "../config/types.js";
